### ISSUE TITLE
Locate does not produces all ambiguous outputs on morphological mode

### ISSUE THREAD

**Issue by fgrandry** [UnitexGramLab/unitex-core#36]
Applying a dictionary-graph with the 'all matches' option doesn't work. Even with the 'a' option, only one analysis is produced.
See posts for more information: [here](https://groups.google.com/forum/?#!topic/unitex-gramlab/KTF563Pxo6I)
Example attached: [dictionary-graph-example.zip](https://github.com/UnitexGramLab/unitex-core/files/1128472/dictionary-graph-example.zip)

Reproduced with version 3.2 alpha dated 27 June 2017

**Comment by martinec** [comment]
Thank you for your bug report. To properly track down the issue, I modified the title from `Dictionary-graphs don't work with the 'all matches' option` to `Locate does not produces all ambiguous outputs on morphological mode`.

Given the corpus:

```
Alph
--
Alphonse
```

After applying the graph `addDiminutives-rba` provided as example, it will be only 1 match: `Alphonse`, so the option `all matches` will always produced a single match.

On the other hand, the latest version of Unitex is producing only 1 output:

```
Al,Alphonse.N+Diminutive
```

However, when matching `Alphonse` inside the morphological mode, the input variable `sub` can store the sequences: `Al`, `Alp`, `Alph` or `Alpho`, and hence there should be 4 **ambiguous outputs** (Unitex User's Manual, p.153):

```
Al,Alphonse.N+Diminutive
Alp,Alphonse.N+Diminutive
Alph,Alphonse.N+Diminutive
Alpho,Alphonse.N+Diminutive
```

This is 1 match and 4 outputs no matter which match policy is in use: longest matches shortest matches or all matches. Taking into account that the current version of Unitex does not implemented the expected behavior, I'm labeling this as a bug.

**Comment by alexis-neme** [comment]
Interesting bug! I am following actively.

Terminological remarks:
"Al" is a nickname or pseudonym of "Alphonso", not a diminutive, which is
"Alfonsino".


Cheers,
